version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/CodHeK/project-Xplore"
  import_paths = [
    "fmt",
    "github.com/gocolly/colly",
    "github.com/gorilla/mux",
    "net/http",
    "html/template",
    "sort",
    "strconv",
    "sync"
  ]
